#!/bin/bash
set -ex

if [ $# -ne 2 ]; then
  echo "Usage: $0 david|localhost comment"
  exit
fi
from=~/Projects/background_shop
to=~/configFiles
branch=$1
comment=$2

cd ${to}
git checkout $branch
for project in Yangtaoabc.{Api,IdServer,Management}; do
  cp ${from}/${project}/appsettings.Development.json ${to}/${project}
done;
git commit -am "${2}"
