#!/bin/bash

# Get git changes
changes=$(git diff -w -b HEAD)

# Exit if no changes
if [ -z "$changes" ]; then
  echo "No changes to commit."
  exit 0
fi

# Set prompt template
prompt_template=$(cat <<-END
You are good at writing git commit messages;
You follow the conventional commits specification:

feat: for new features
chore: for maintenance work
fix: for bug fixes

You need to write a commit message for the changes from `git diff` command.
please summarize the changes and write a short commit message.
you should try to summerize all meaningful changes while keep the result short.
THE RESULT SHOULD ONLY BE NO MORE THEN 80 CHARACTERS.
here is a Example response, but DO NOT return it as your result.

feat: added new disabled boolean variable to button

do not include any other information/text rather than the commit message itself.
and here's the changes:

END
)

prompt_template+="$changes"

# Build JSON request body using jq
request_body=$(jq -n --arg model "gpt-4o-mini-2024-07-18" --arg prompt "$prompt_template" \
  '{model: $model, messages: [{role:"system",content:"You are a programmer"},{role: "user", content: $prompt}], max_tokens: 50, seed: 45, temperature: 0}')

# Use curl to request the OpenAI API to generate a commit message
response=$(curl -s --request POST \
  --url https://api.openai.com/v1/chat/completions \
  --header "Authorization: Bearer $OPENAI_API_KEY" \
  --header "Content-Type: application/json" \
  --data "$request_body")

# Extract commit message from the response
commit_message=$(echo "$response" | jq -r '.choices[0].message.content')

# Exit if the commit message is empty
if [ -z "$commit_message" ]; then
  echo 'failed to generate a commit message'
  exit 1
fi

# Commit changes
git commit -am "$commit_message"

