#!/usr/bin/bash

set -e
find . -iname "bin" -print0 | xargs -0 echo
find . -iname "obj" -print0 | xargs -0 echo
read -p "The above folders are going to be deleted, are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]; then
    find . -iname "bin" -print0 | xargs -0 rm -rfv
    find . -iname "obj" -print0 | xargs -0 rm -rfv
    echo done
else
    echo no
    exit 1
fi
