#!/bin/bash

logFile=/tmp/deleteAccount.log
phoneNumber=$1
sqlFile=~/bin/deleteAccount.SQL
sqlStatements=$(cat $sqlFile | sed 's/place-holder/'${phoneNumber}'/g')
TZ="Pacific/Auckland" date '+%Y-%m-%d %H:%M:%S' >> $logFile
echo $sqlStatements | tee -a $logFile | mysql
echo >> $logFile
echo The account for Mobile: $phoneNumber has been removed Done.
