#!/bin/bash

currentbranch=`git branch --show-current`
git pull --ff
git push
[ $? -eq 0 ] || echo "push $currentbranch failed!"
if [ "${currentbranch}" == "local" ]; then
   git checkout develop
   git pull --ff
   git merge local
   git push
   [ $? -eq 0 ] || echo push develop failed!

   git checkout master
   git pull --ff
   git merge local
   git push
   [ $? -eq 0 ] || echo push local failed!
elif [ "${currentbranch}" == "develop" ]; then
   git checkout local
   git pull --ff
   git merge develop
   git push
   [ $? -eq 0 ] || echo push local failed!

   git checkout master
   git pull --ff
   git merge develop
   git push
   [ $? -eq 0 ] || echo push master failed!
fi
git checkout $currentbranch
