#!/bin/bash

# 定义本地备份目录和远程目标目录
local_dir="/backup/ebook"
remote_user="user"
remote_host="192.168.168.125"
remote_port="2222"
remote_dir="/sdcard"
remote_screenshots_dir="/sdcard/koreader/screenshots"
local_screenshots_dir="/backup/koreader"

# 使用rsync进行增量同步
rsync -avz --inplace --no-perms --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' $local_dir $remote_user@$remote_host:$remote_dir

rsync -avz --inplace --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' $remote_user@$remote_host:$remote_screenshots_dir $local_screenshots_dir

